title: Issues to Blog
subtitle: Because laziness is the mother of invention
author: author
# avatar_url: https://en.gravatar.com/userimage/139060802/b01cf77915709dca9a78ade7dbecc842.png?size=160 # Should be 160x160px.
# email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
description: > # this means to ignore newlines until "twitter_username:"
  blar
  blar
  blar
repository: jcansdale/IssuesToBlog

# contact
contact:
#  email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
  url: https://jcansdale.github.io/IssuesToBlog/issues/new # Uncomment this to provide a contact form url instead of an email

# social links
twitter_username: jcansdale
github_username:  jcansdale
rss: rss

# 
# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
feed:
   path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
# subscribe_rss: http://feeds.jcansdale.com/jcansdale

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: true
  show_count: true
#  receiver: https://jcansdale.azurewebsites.net/api/PostComment  # See https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/ for more information.

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"
category_dir: categories

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: jcansdale/haackbar

exclude: [README.md CODE_OF_CONDUCT.md script .gitattributes .gitignore keybase.txt RakeFile]
keep_files: [images demos code ads.txt robots.txt favicon.ico]
incremental: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
theme: jekyll-theme-slate
